version: "3.9"

services:

  api:
    build: ./api
    ports:
      - "8000:8000"
  rabbitmq:
    image: rabbitmq:3.9.12-management
    ports:
      - "5672:5672"
      - "15672:15672"

  prometheus:
    image: prom/prometheus:v2.32.1
    volumes:
      - ./prometheus/:/etc/prometheus
    ports:
      - "9090:9090"
    depends_on:
      - cadvisor

  node-exporter: 
    image: prom/node-exporter:v1.3.1
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
    - '--path.procfs=/host/proc' 
    - '--path.sysfs=/host/sys'
    - --collector.filesystem.ignored-mount-points
    - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    ports:
      - "9100:9100"

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.39.3
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - "8080:8080"
  # web:
    # build: ./client
    # ports:
      # - "80:80"

# volumes:
  # prometheus_data: {}